### ISSUE TITLE
Pod Travis

### ISSUE THREAD

**Issue by fortmarek** [keefertaylor/MnemonicKit#9]
Automate pod releases with travis.
Add 
`pod trunk push`
`api_key`
`pod lib lint`

Note that `pod lib lint` works only from version 1.6.0 of cocoapods that is in beta as of now (I had problem with this [https://github.com/CocoaPods/CocoaPods/issues/7708](issue))

**Comment by keefertaylor** [comment]
We should also investigate making Carthage deploy automatically, it fails here: 
https://travis-ci.org/keefertaylor/MnemonicKit/builds/476648071

**Comment by fortmarek** [comment]
Could you point me to the line where it fails? What does not work about Carthage, though, is that there is not set `skip_cleanup: true`, so it delete the archived framework. Once that's added, it should work just fine.

**Comment by keefertaylor** [comment]
The build errors with 'missing api key'. Presumably it needs my github credentials as opposed to something Carhtage specific. Sorry for mis-typing.
